//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int IDPurchase { get; set; }
        public System.DateTime DatePurchase { get; set; }
        public System.DateTime DateExpire { get; set; }
        public int Cost { get; set; }
        public int IDUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
